# Generated by Django 3.0.8 on 2020-07-30 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200722_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='belongs_to',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL, verbose_name='belongs_to'),
        ),
    ]
