# Generated by Django 3.0.8 on 2020-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200731_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_link',
            field=models.CharField(default='default_product_thumbnail.png', max_length=250, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(default='default_product_thumbnail.png', help_text='Please complete the above URL', verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='image_link',
            field=models.CharField(default='default_metadata_image.png', max_length=250, verbose_name='image_link'),
        ),
    ]
