# Generated by Django 3.0.5 on 2020-04-07 14:15
import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200506_1737'),
    ]

    def generate_superuser(apps, schema_editor):
        from api.models import Identity
        superuser = Identity.objects.create_superuser(
            username='admin',
            email=os.environ.get('DJANGO_SU_EMAIL', 'admin@example.com'),
            password=os.environ.get('DJANGO_SU_EMAIL', 'admin'))

        superuser.save()


    operations = [
        migrations.RunPython(generate_superuser),
    ]
