# Generated by Django 3.0.8 on 2020-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200803_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='order_index'),
        ),
        migrations.AlterField(
            model_name='userchange',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='userchange',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first_name'),
        ),
    ]
