# Generated by Django 3.0.5 on 2020-04-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200415_0926'),
    ]

    migration = '''
        CREATE TRIGGER ts_search_update BEFORE INSERT OR UPDATE
        ON product FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(ts, 'pg_catalog.french', label);

        -- Force triggers to run and populate the ts column.
        UPDATE product set ID = ID;
    '''

    reverse_migration = '''
        DROP TRIGGER ts_search ON product;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
