# Generated by Django 3.0.5 on 2020-04-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0007_auto_20200421_0951'), ('api', '0008_auto_20200421_1338')]

    dependencies = [
        ('api', '0006_auto_20200415_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='modified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_user', to=settings.AUTH_USER_MODEL, verbose_name='modified_user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='id_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_contact', to=settings.AUTH_USER_MODEL, verbose_name='invoice_contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_contact', to=settings.AUTH_USER_MODEL, verbose_name='order_contact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PUBLISHED_ONLY_IN_GROUP', 'Published only in group'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=30, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='MetadataContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_role', models.CharField(blank=True, max_length=150, verbose_name='role')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='contact_person')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Metadata', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'metadata_contact_persons',
            },
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='contact_persons',
        ),
        migrations.AddField(
            model_name='metadata',
            name='contact_persons',
            field=models.ManyToManyField(related_name='contact_persons', through='api.MetadataContact', to=settings.AUTH_USER_MODEL, verbose_name='contact_persons'),
        ),
        migrations.AlterModelTable(
            name='metadatacontact',
            table='metadata_contact_persons',
        ),
    ]
