# Generated by Django 3.0.5 on 2020-05-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200421_0951_squashed_0008_auto_20200421_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatacontact',
            options={'verbose_name': 'metadata_contact'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'product'},
        ),
        migrations.AddField(
            model_name='identity',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_contact', to=settings.AUTH_USER_MODEL, verbose_name='invoice_contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_contact', to=settings.AUTH_USER_MODEL, verbose_name='order_contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part_vat',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CHF', max_digits=14, null=True, verbose_name='part_vat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='processing_fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CHF', max_digits=14, null=True, verbose_name='processing_fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CHF', max_digits=14, null=True, verbose_name='total_cost'),
        ),
    ]
