# Generated by Django 3.0.8 on 2020-08-11 14:45

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitem_extract_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extract_result',
            field=models.FileField(blank=True, null=True, upload_to=api.helpers.RandomFileName('extract')),
        ),
    ]
