# Generated by Django 3.0.8 on 2020-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200814_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sap_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='sap_id'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='SITN', max_length=30, verbose_name='provider'),
        ),
    ]
