# Generated by Django 3.0.5 on 2020-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200604_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='street')),
                ('street2', models.CharField(blank=True, max_length=100, verbose_name='street2')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='postcode')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='company_name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'user_change',
                'db_table': 'user_change',
            },
        )
    ]
