# Generated by Django 3.0.5 on 2020-06-26 13:53

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200609_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='name',
            field=models.CharField(default='pricing_name', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='pricing_area_name',
            field=models.CharField(max_length=100, null=True, verbose_name='pricing_area_name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(default='https://sitn.ne.ch/web/documents', help_text='Please complete the above URL', verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricing_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('SINGLE', 'Single'), ('BY_NUMBER_OBJECTS', 'By number of objects'), ('BY_AREA', 'By area'), ('FROM_PRICING_LAYER', 'From a pricing layer'), ('MANUAL', 'Manual')], max_length=30, verbose_name='pricing_type'),
        ),
        migrations.AlterField(
            model_name='pricingarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=2056, verbose_name='geom'),
        ),
        migrations.AddIndex(
            model_name='pricingarea',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='pricing_lay_name_23aff9_btree'),
        ),
    ]
