# Generated by Django 3.0.5 on 2020-06-26 14:46

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200626_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingarea',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pricingarea',
            name='unit_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='CHF', max_digits=14, null=True, verbose_name='price'),
        ),
    ]
