# Generated by Django 3.0.8 on 2020-10-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201009_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingArea',
            new_name='PricingGeometry',
        ),
    ]
