# Generated by Django 3.0.8 on 2020-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201014_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_when_subscribed',
            field=models.BooleanField(default=False, verbose_name='free_when_subscribed'),
        ),
    ]
