# Generated by Django 3.0.8 on 2020-12-08 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_product_free_when_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchange',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='client'),
            preserve_default=False,
        ),
    ]
