# Generated by Django 3.0.5 on 2020-06-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200629_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'pricing'},
        ),
        migrations.AlterModelOptions(
            name='productvalidation',
            options={'verbose_name': 'product_validation'},
        ),
        migrations.AlterModelTable(
            name='pricing',
            table='pricing',
        ),
        migrations.AlterModelTable(
            name='productvalidation',
            table='product_validation',
        ),
    ]
