# Generated by Django 3.0.8 on 2020-12-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_free_when_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='subscribed'),
        ),
    ]
