# Generated by Django 3.0.8 on 2020-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacontact',
            name='metadata_role',
            field=models.CharField(default='Gestionnaire', max_length=150, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('READY', 'Ready'), ('IN_EXTRACT', 'In extract'), ('PARTIALLY_DELIVERED', 'Partially delivered'), ('PROCESSED', 'Processed'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='status'),
        ),
    ]
