# Generated by Django 3.0.8 on 2021-01-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210108_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(default='', help_text='Please complete the above URL', max_length=2000, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
