# Generated by Django 3.0.8 on 2021-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210226_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='datasource',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='datasource'),
        ),
    ]
