# Generated by Django 3.0.8 on 2021-04-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_metadata_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='download_guid'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='image_link',
            field=models.CharField(blank=True, default='default_metadata_image.png', max_length=250, verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.OrderType', verbose_name='order_type'),
            preserve_default=False,
        ),
    ]
