# Generated by Django 3.0.8 on 2021-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210409_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_deliver',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email_deliver'),
        ),
    ]
