# Generated by Django 3.0.8 on 2021-05-10 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_order_email_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.CharField(max_length=30, verbose_name='provider', null=True),
        )
    ]
