# Generated by Django 3.2.8 on 2021-12-21 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20211221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(message='Label contains forbidden characters', regex='^[^<>%$"\\(\\)\\n\\r]*$')], verbose_name='label'),
        ),
    ]
