# Generated by Django 3.2.8 on 2022-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='accessibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('APPROVAL_NEEDED', 'Approval needed'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=30, verbose_name='accessibility'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='token',
            field=models.CharField(blank=True, null=True, verbose_name='token', max_length=256),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('VALIDATION_PENDING', 'Validation pending'), ('PENDING', 'Pending'), ('IN_EXTRACT', 'In extract'), ('PROCESSED', 'Processed'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
