# Generated by Django 3.2.10 on 2022-01-05 16:28

from django.db import migrations, models
import django.db.models.deletion

def default_product_metadata(apps, schema_editor):
    """Sets to generic metadata when product doesn't have one"""
    Metadata = apps.get_model('api', 'Metadata')
    Product = apps.get_model('api', 'Product')
    db_alias = schema_editor.connection.alias
    generic_metadata_id = Metadata.objects.using(db_alias).filter(id_name='00_generic_metadata').first()
    if generic_metadata_id:
        Product.objects.using(db_alias).filter(metadata__isnull=True).update(
            metadata=generic_metadata_id
        )

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_orderitem_validation_date'),
    ]

    operations = [
        migrations.RunPython(default_product_metadata, reverse),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.metadata', verbose_name='metadata'),
            preserve_default=False,
        ),
    ]
