# Generated by Django 3.2.12 on 2022-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_product_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacontact',
            name='is_validator',
            field=models.BooleanField(default=False, verbose_name='is_validator'),
        ),
    ]
