# Generated by Django 3.2.12 on 2022-04-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0039_alter_product_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'extract'}, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='provider'),
        ),
    ]
