# Generated by Django 3.2.12 on 2022-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_product_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='accessibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('APPROVAL_NEEDED', 'Approval needed'), ('NOT_ACCESSIBLE', 'Not accessible'), ('INTERNAL', 'Internal')], default='PUBLIC', max_length=30, verbose_name='accessibility'),
        ),
    ]
