# Generated by Django 3.2.13 on 2022-07-27 11:37

from django.db import migrations


def add_ech_categories(apps, schema_editor):
    MetadataCategoryEchModel = apps.get_model('api', 'MetadataCategoryEch')
    MetadataCategoryEchModel.objects.bulk_create([
        MetadataCategoryEchModel(notation="A1", description_fr="Cartes de référence, modèles du territoire"),
        MetadataCategoryEchModel(notation="A2", description_fr="Couverture et utilisation du sol"),
        MetadataCategoryEchModel(notation="A3", description_fr="Images aériennes et satellitaires"),
        MetadataCategoryEchModel(notation="B", description_fr="Localisation, systèmes de référence"),
        MetadataCategoryEchModel(notation="C", description_fr="Altimétrie"),
        MetadataCategoryEchModel(notation="D", description_fr="Limites politiques et administratives"),
        MetadataCategoryEchModel(notation="E1", description_fr="Développement territorial"),
        MetadataCategoryEchModel(notation="E2", description_fr="Cadastre foncier"),
        MetadataCategoryEchModel(notation="F1", description_fr="Géologie"),
        MetadataCategoryEchModel(notation="F2", description_fr="Sols"),
        MetadataCategoryEchModel(notation="F3", description_fr="Dangers naturels"),
        MetadataCategoryEchModel(notation="G", description_fr="Forêt, flore, faune"),
        MetadataCategoryEchModel(notation="H", description_fr="Océans"),
        MetadataCategoryEchModel(notation="I", description_fr="Hydrographie"),
        MetadataCategoryEchModel(notation="K", description_fr="Atmosphère, climatologie"),
        MetadataCategoryEchModel(notation="L1", description_fr="Protection de l'environnement, bruit"),
        MetadataCategoryEchModel(notation="L2", description_fr="Protection de la nature et du paysage"),
        MetadataCategoryEchModel(notation="M", description_fr="Population, société, culture"),
        MetadataCategoryEchModel(notation="N", description_fr="Santé"),
        MetadataCategoryEchModel(notation="O", description_fr="Edifices, infrastructures, ouvrages"),
        MetadataCategoryEchModel(notation="P", description_fr="Transport"),
        MetadataCategoryEchModel(notation="Q1", description_fr="Energie"),
        MetadataCategoryEchModel(notation="Q2", description_fr="Systèmes des eaux et des déchets"),
        MetadataCategoryEchModel(notation="Q3", description_fr="Communication"),
        MetadataCategoryEchModel(notation="R", description_fr="Armée, sécurité"),
        MetadataCategoryEchModel(notation="S", description_fr="Agriculture"),
        MetadataCategoryEchModel(notation="T", description_fr="Activités économiques"),
    ])

def del_ech_categories(apps, schema_editor):
    MetadataCategoryEchModel = apps.get_model('api', 'MetadataCategoryEch')
    MetadataCategoryEchModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220727_1327'),
    ]

    operations = [
        migrations.RunPython(add_ech_categories, del_ech_categories)
    ]
