# Generated by Django 4.1 on 2022-11-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_metadata_geoportal_link_metadata_wms_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="data_last_update_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="data_last_update_date"
            ),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="ech_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.metadatacategoryech",
                verbose_name="ech_category",
            ),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="id_name",
            field=models.CharField(max_length=100, unique=True, verbose_name="id_name"),
        ),
    ]
