# Generated by Django 4.1 on 2023-02-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_metadata_data_last_update_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadata",
            options={
                "permissions": [
                    (
                        "view_internal",
                        'Can view metadata with accessibility set to "internal"',
                    )
                ],
                "verbose_name": "metadata",
            },
        ),
    ]
