FROM node:22.21.1-slim

WORKDIR /usr/app

COPY package*.json ./.
RUN --mount=type=cache,target=/root/.npm npm install --legacy-peer-deps

EXPOSE 4200
CMD ["npm", "start", "--", "--host=0.0.0.0", "--disable-host-check"]
